name: CI - Public

on:
  push:
    branches:
      - master
    paths:
      - 'public/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
        working-directory: ./public
      - name: Build
        run: npm run build
        working-directory: ./public
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "default"
          PROJECT_PATH: "./public"
